name: Weekly RVO Blog Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run blog sync
        run: python rvo_blog_sync.py

      - name: Upload data artifact
        uses: actions/upload-artifact@v2
        with:
          name: blog-data
          path: data/rvo_blogs.jsonl
